services:
  - type: web
    name: virtual-cosmos
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: MONGODB_URI
        sync: false
